name: zoom_app
description: Este projeto foi elaborado como proposta de demonstração do aprendizado do curso de GeneXus ministrado pelo Fabio Visquete da FMX Soluções Tecnológicas. Patrick Neri - Desenvolvimento do APP Flutter. Ewerton Moura - Desenvolvimento do Dashboard Power BI. Ambos participaram do desenvolvimento da aplicação GX.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_notch_bottom_bar: ^0.0.4
  flutter_svg: ^1.1.5
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/navbar/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
